### ISSUE TITLE
Dependências faltando no packages.json

### ISSUE THREAD

**Issue by paulocsanz** [ffarzat/FakeSIGA#18]
Estão faltando as seguintes dependências no packages.json: compression e helmet sem elas não é possível executar o servidor.

Basta adicionar essas linhas nas dependências do packages.json do servidor pra resolver:
`    "compression": "^1.6.2",`
`    "helmet": "^3.1.0",`

Para replicar basta clonar o repositório, instalar suas dependências e executar o servidor (checando que as dependências não estão salvas globalmente), que retorna o seguinte erro:
`Error: Cannot resolve path "compression"`

Ao instalar a dependencia compression com `npm install --save compression`, adicionando ao packages.json e executar o servidor é retornado o seguinte erro:
`Error: Cannot resolve path "helmet"`

Após adicionar o helmet, com o mesmo comando do anterior, o problema é resolvido e o servidor roda normalmente.

**Comment by ffarzat** [comment]
@paulocsanz , muito obrigado. Vou incluir as refs.

**Comment by ffarzat** [comment]
Feito.
